// Path to IdExtenso entry point.
// ---
#include '../$$.jsxinc'

// L10N is powered by YALT.
// ---
#include '../etc/$$.Yalt.jsxlib'

// Collator module.
// ---
#include '../etc/$$.Collator.jsxlib'

$$.Yalt.addPackage
(
"""
	/*<YALT> # FRENCH # GERMAN # SPANISH # ITALIAN # RUSSIAN

	Ignore Punctuation # Ignorer la ponctuation # Interpunktion ignorieren # Ignorar la puntuación # Ignora la punteggiatura # Игнорировать Пунктуация
	Sort Depth # Profondeur de tri # Sortierstufe # Nivel de ordenación # Livello di ordinamento # Уровень сортировки
	
	Ignore case and diacritics # Ignorer casse et diacritiques # Großschreibung und diakritische Zeichen ignorieren # Ignorar mayús./minús. y signos diacríticos # 1 - Ignora maiuscole/minuscole e segni diacritici # Игнорировать регистр и диакритические
	Ignore case # Ignorer la casse # Großschreibung ignorieren # Ignorar mayús./minús. # Ignora maiuscole/minuscole # Игнорировать регистр
	Full Sort # Tri complet # Voll sortieren # Ordenar completa # Sorta completa # Полный сортировать

	</YALT>*/
"""
);

// Load the framework.
// ---
$$.load();

// =============================================================================
// CollatorTester [200531]
// Live-test IdExtenso's collation module in various languages.
// ---
// Demonstrates:
// - Using the `Collator` module.
// - Adding a YALT package.
// - Simple modal dialog interface generated by `ScriptUI.builder`.
// =============================================================================

try
{
	const UI = function UI(  w)
	//----------------------------------
	{
		w = ScriptUI.builder.call(callee,callee.RES);
		w.show();
	};
	
	UI.TEST_ITEMS = "!RAË|-braender|.hello|A.B.C|ABBA|ABN|AERO|Abner|Abnég.|Brad|Bränder, Hans|Ca|Ce|Da|De|Dorfer, J.|Dörfener, F.|DŽa|DŽe|Eros|HB|Ha|Hi!|Hé|I.N.A.|IJmuiden|Ih!|Ikea|LA|LAWR|LJA|LLOM|LLONG|LLONGYFARCH|LWCUS|MA|Mueller, G.|Muller, E.|Muller, I.|Müller, F.|Müller, H.|O.J.|Oh|ab ner|abc|altså|aéré|bot|braender|brand|bras|broc|bryst|brænder|brød|buzhugenn|c'hoar|c:/ab|chispa|chug|cinco|cote|credo|côte|côté|côté|daeraouenn|fjord|he|hip hop|hip-hop|in punto|jeg|law|llama|locus|lomo|luz|ohé|ordet|radio|rana|rap|rastrillo|robot|roc|ráfaga|rápido|vild|Ãlto|Åbner|Ça|Ère|åbner|ære|çà|è|øje|Ća|Će|ĉa|ĉe|ĉote|Ča|Če|Đa|Đe|весь|вот|говорить|год|для|как|который|на|не|он|сказать|такой|уже|что";
	
	// Some static settings.
	// ---
	UI.TITLE = "Collator Tester";
	UI.MARGINS = 22;

	UI.ON_WSHW = function onShow(  wg,q,s)
	//----------------------------------
	// this :: Window (Dialog)
	{
		(wg=this.List).active = true;
		q = wg.properties.items;
		s = q['='+$$.Collator.getLocaleKey('asIso')];
		wg.selection = wg.find(s)||0;
		wg.onChange();
	};

	UI.ON_LCHG = function onChange(  q,s,tk,bullet,nv)
	//----------------------------------
	// this :: DropDownList [`List`]
	{
		q = this.properties.items;
		s = this.selection.text;

		tk = q['_'+s];
		$$.Collator.setTailor(tk);

		bullet = ( 'ROOT'==tk || 'EOR'==tk ) ? '\u25B7' : '\u25B6';
		nv = q['§'+s];
		nv==tk ? (nv='') : (nv=' '+nv);
		
		this.window.Info.text = bullet + nv + '  [' + tk + ']';
	};
	
	UI.ON_BCLK = function onClick(  w,ed,a)
	//----------------------------------
	// this :: Button [`Sort`]
	{
		w = this.window;

		ed = w.Strings;
		a = ed.text.split(RegExp.LINEs);

		$$.Collator(a,1+w.Level.selection.index,!w.IgnorePunct.value);
		ed.text = a.join('\r');
	};
	
	// UI resource object.
	// ---
	UI.RES =
	{
		properties:                     { type:'dialog', text:UI.TITLE, },
		margins:                        UI.MARGINS,
		spacing:                        UI.MARGINS,
		orientation:                    'row',
		alignChildren:                  ScriptUI.LT,
		onShow:                         UI.ON_WSHW,

		Group$0:
		{
			properties:                 { },
			margins:                    0,
			spacing:                    40,
			orientation:                'column',
			alignChildren:              ScriptUI.CT,

			Group$GpLang:
			{
				margins:                0,
				spacing:                6,
				orientation:            'column',

				StaticText$Lang:
				{
					properties:         { text:__("Language:") },
					optimalSize:        { width:220, height:24 },
				},

				DropDownList$List:
				{
					properties:         { items:$$.Collator.getRichList() },
					optimalSize:        { width:220, height:24 },
					onChange:           UI.ON_LCHG,
				},

				StaticText$Info:
				{
					properties:         { text:'' },
					optimalSize:        { width:220, height:24 },
				},

			},

			Group$GpSort:
			{
				margins:                0,
				spacing:                6,
				orientation:            'column',

				StaticText$0:
				{
					properties:         { text:__("Sort Depth:") },
					optimalSize:        { width:220, height:24 },
				},

				DropDownList$Level:
				{
					properties:         { items:
						[
						__( "(%1) %2", '1', __("Ignore case and diacritics") ),
						__( "(%1) %2", '2', __("Ignore case") ),
						__( "(%1) %2", '3', __("Full Sort") )
						] },
					optimalSize:        { width:220, height:24 },
					selection:          2,
				},

				CheckBox$IgnorePunct:
				{
					properties:         { text:__("Ignore Punctuation") },
					optimalSize:        { height:24 },
					alignment:          ScriptUI.RC,
					value:              true,
				},

			},
			
			Group$Buttons:
			{
				margins:                0,
				orientation:            'row',
				spacing:                UI.MARGINS,
				alignChildren:          ScriptUI.CB,
				
				Button$Quit:
				{
					properties:         { text:__("Quit"), name:'OK' },
					minimumSize:        { width: 80 },
				},

				Button$Sort:
				{
					properties:         { text:__("Sort") + " >>>" },
					minimumSize:        { width: 100 },
					onClick:            UI.ON_BCLK,
				},
			},

		},

		Panel$1:
		{
			properties:                 { text:__("List:"), },
			margins:                    UI.MARGINS,
			spacing:                    16,
			orientation:                'column',

			EditText$Strings:
			{
				properties:             { text:UI.TEST_ITEMS.split('|').join('\r'), multiline:true },
				optimalSize:            { width:200, height:320 },
			},
		},
	};
	
	// Send events to be listened to and show.
	// ---
	UI();
}
catch(e)
{
	// Should something go wrong.
	// ---
	$$.receiveError(e);
}
// =============================================================================


// Unload the framework to cleanup memory.
// ---
$$.unload();