// Path to IdExtenso entry point.
// ---
#include '../$$.jsxinc'

// UniAsc module.
// ---
#include '../etc/$$.UniAsc.jsxlib'

// Load the framework.
// ---
$$.load();

// =============================================================================
// UnicodeToAscii [220402]
// Basic transliteration module.
// ---
// Demonstrates:
// - Using the `UniAsc` module.
// - Simple modal dialog interface generated by `ScriptUI.builder`.
// =============================================================================

try
{
	var init = 'まさゆき たけだ';
	ScriptUI.builder
	({
		properties:                     { type:'dialog', text:"UniAsc Tester", },
		margins:                        22,
		spacing:                        22,
		orientation:                    'column',
		alignChildren:                  ScriptUI.LT,

		Panel$1:
		{
			properties:                 { text:'', },
			margins:                    22,
			spacing:                    10,
			orientation:                'column',
			alignChildren:              ScriptUI.LT,
			
			StaticText$0:               { properties:{text:"Unicode string:"} },

			EditText$Input:
			{
				properties:             { text:init, multiline:true },
				optimalSize:            { width:400, height:60 },
				onChanging:             function onChanging( w)
				{
					w = this.window;
					w.Info.text = this.text.translit();
				},
			},

			StaticText$1:               { properties:{text:"ASCII Translit.:"} },

			EditText$Info:
			{
				properties:             { text:init.translit(), multiline:true, readonly:true },
				optimalSize:            { width:400,height:60 },
			},
		},

		Group$2:
		{
			margins:                    22,
			spacing:                    20,
			orientation:                'row',
			alignment:                  ScriptUI.CT,

			Button$Quit:
			{
				properties:             { text:'Quit', name:'cancel' },
			}
		},		
	})
	.show();
}
catch(e)
{
	// Should something go wrong.
	// ---
	$$.receiveError(e);
}
// =============================================================================


// Unload the framework to cleanup memory.
// ---
$$.unload();